# Generated by Django 2.1.15 on 2019-12-07 14:23

from django.db import migrations, models
import django.db.models.deletion
import ecount.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('품목코드', models.CharField(max_length=20)),
                ('품목명', models.CharField(max_length=20)),
                ('품목구분', models.CharField(max_length=20)),
                ('색상', models.CharField(blank=True, max_length=20)),
                ('단위', models.CharField(blank=True, max_length=20)),
                ('개수', models.IntegerField()),
                ('입고단가', models.IntegerField()),
                ('이미지', models.ImageField(blank=True, upload_to=ecount.utils.uuid_upload_to)),
                ('내용', models.TextField(blank=True)),
                ('생성시간', models.DateTimeField(auto_now_add=True)),
                ('수정시간', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('거래처코드', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('거래처명', models.CharField(max_length=20)),
                ('내용', models.TextField()),
                ('생성시간', models.DateTimeField(auto_now_add=True)),
                ('수정시간', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='거래처코드',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Shop'),
        ),
    ]
